name: Backstage Renovate Changeset Creator
description: Create changesets on the renovate bot PR's if needed
inputs:
  multiple-workspaces:
    description: If it's this repository is a collection of workspaces
    required: false
    default: 'false'
  includeDevDependencies:
    description: If devDependency changes should be included
    required: false
    default: 'true'

outputs: {}
runs:
  using: node20
  main: ./entry.js
