name: Backstage Cron
description: Repository operations on a schedule
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
outputs: {}
runs:
  using: node16
  main: ./entry.js
