name: Cron
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: backstage/actions/cron@v0.1.10
        with:
          app-id: '165448'
          private-key: ${{ secrets.BACKSTAGE_GOALIE_PRIVATE_KEY }}
