name: PR Review Comment Trigger
on:
  pull_request_review_comment:
    types:
      - created

jobs:
  upload:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: >-
        ( github.event.pull_request || github.event.issue.pull_request )
        && github.context.actor == github.context.payload.pull_request.user.login

    # A failed workflow signals that we need to re-review
    steps:
      - uses: hmarr/debug-action@v2
      - run: exit 1
