name: PR Comment
on:
  pull_request_review_comment:
    types:
      - created

jobs:
  upload:
    runs-on: ubuntu-latest

    # Avoid running on issue comments
    if: >-
        ( github.event.pull_request || github.event.issue.pull_request )
        && github.context.actor == github.context.payload.pull_request.user.login

    steps:
      - name: Dummy
        run: echo "Triggering PR review comment workflow"
