name: PR
on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: backstage/actions/pr-sync@v0.2.3
        with:
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
          board-number: 2
