name: PR Sync
on:
  pull_request_target:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: backstage/actions/pr-sync@v0.1.6
        with:
          github-token: ${{ secrets.GH_SERVICE_ACCOUNT_TOKEN }}
